Eessi2-329 konfigurasjon og setup av eslint airbnb
navikt/melosys-web pull request #14
Opened 2017-10-03 14:44 UTC by abjolseth

2017-10-03 18:16 UTC, abjolseth commented
OK, før Prettier
const fnrValid = value => (
  /^[0-9]{11}$/.test(value) ? undefined : 'Fnr må ha 11 siffer'
);
FEIL, etter prettier
const fnrValid = value =>
    /^[0-9]{11}$/.test(value) ? undefined : 'Fnr må ha 11 siffer';

2017-10-04 06:42 UTC, terjeofnorway requested changes
Ser topp ut! Jeg har testet og alt ser ut til å fungere/linte korrekt hos meg.

Forslag:
- Legge til .lesshintrc i rot slik at vi i fremtiden kan definere unntak eller exlusions om nødvendig.

Spørsmål:
- Vi reverserer "2precommit" når vi har fått lintingen på plass, sant?

2017-10-04 08:42 UTC, terjeofnorway approved these changes

2017-10-04 12:57 UTC, abjolseth commented on .lesshintrc
> +  "excludedFiles": ["arbeidsforholdd.less"]
Hvorfor trenger vi å exclude? Kan vi ikke slette, og eller flytte innhold?

2017-10-04 13:02 UTC, abjolseth commented on src/Arbeidsforhold.js
> +      hentSaksopplysninger: PT.func.isRequired,
Her bør vi lage en shape

2017-10-04 21:40 UTC, abjolseth commented
Self ACK. Testet, tweeket, og pyntet.

2017-10-04 21:40 UTC, merged