Legger til støtte for å journalføre dokument på virksomhet.
navikt/melosys-web pull request #1458
Opened 2022-04-04 13:26 UTC by janitamarielle

Legger til støtte for å journalføre dokument på virksomhet.
- Man kan velge mellom å journalføre på bruker og virksomhet. Dette har endel følger lengre nedover i journalføringsbildet.
- Man kan nå hente fagsaker basert på orgnr i tillegg til ident og saksnummer.

https://jira.adeo.no/browse/MELOSYS-4896

Melosys-api: https://github.com/navikt/melosys-api/pull/1122 ✅ 
Melosys-docker-compose: https://github.com/navikt/melosys-docker-compose/pull/38 ✅

2022-04-20 15:28 UTC, IsaSalemHame requested changes

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +  avsenderID: string().when(["avsenderType", "$erAvsenderPreutfylt", "journalføresPå"], {
Avsender bør resettes når man bytter mellom Bruker og virksomhet. Dersom man f.eks. begynner å journalføre på person, velger f.eks. `Utenlandsk trygdemyndighet`, for så å gå til Virksomhet og ikke velge hverken "Virksomhet" eller "Fullmektig", så vil det fortsatt gå an å journalføre

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/informasjon.js
> +        </>
Vi skulle ikke hatt litt mer spacing mellom her og "Informasjon om avsender"? Ligger veldig tett føler jeg. Mulig det var sånn før også, men virker å være mer spacing i skissene.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/informasjon.js
>          <Mui.Undertittel tekst="Informasjon om avsender" ikon={Ikoner.Globe} className="undertittel" />
Det er annerledes ikon i skissene. Samt. er det understrek under hver overskrift. Skulle vi kanskje fått slike designendringer i egen PR, hvis det ikke har kommet egen task på det?

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/avsendere.js
>  export const AvsenderOrganisasjon = ({
Annerledes design mellom her og skissene. Igjen, egen task, eller her?

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/journalforing.js
> +      virksomhetOrgnr: !journalføresPåBruker ? virksomhetOrgnr : null,
Trenger man å ha if-setting her? Er ikke verdien null hvis ikke det eksisterer?

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/journalforing.js
> +    const { navn = "" } = response.data;
Er det egentlig noe vits med `= ""`? Bør ikke ha noe å si for if-sjekken, såvidt jeg kan se.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/journalforing.js
> +    await hentFagsakListeForOrgnr(virksomhetOrgnr);
Lurer på om hentFagsakListeForOrgnr og hentFagsakListeForFnr burde ut av disse metodene. Slik jeg skjønner, så går denne videre til JournalføringForm, og videre inn i Informasjon.js (som forsåvidt jeg synes er litt dårlig navn). Jeg mener at den som kaller på metoden burde få en promise, som så kaller på hentFagsakListeForOrgnr.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/avsendere.js
> +export const AvsenderFullmektig = ({
Forskjellige avsendere burde egentlig bare ha egne filer, kanskje i egen mappe med en index.js. Litt vanskelig å vite at det finnes flere komponenter i samme fil..

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/avsendervelger.js
> +            {formValues.avsenderType === KV.AvsenderTyper.ARBEIDSGIVER && (
Hvis du bare refresher siden, og trykker på denne, så kommer feil i console:
`Warning: Failed prop type: The prop `journalføresPåVirksomhet` is marked as required in `AvsenderOrganisasjon`, but its value is `undefined`.`

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/komponent.tsx
> +const Komponent = ({ ikon: Ikon, tittel, innhold }: KomponentProps) => {
Er det ikke bedre å kalle det JournalføringKomponent? Da er det litt lettere å se hva "Komponent" er når man randomly er inne på denne komponenten.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/dokumentetJournalføresPå.tsx
> +const DokumentetJournalføresPå = ({ journalføresPå, oppdaterFelt, defaultBrukerID }: PropsFromRedux) => {
Tror ikke vi har noen andre filer med æ ø å. Burde kanskje fortsette med det, bare for å være konsistent. Vet ikke om det er derfor, men ser faktisk ut som det ødelegger for Pull Requests i IntelliJ.

Skulle helst ha kalt det noe annet også, kanskje "JournalføringRolleVelger" eller noe sånt. Føler komponenten som det heter nå er mer en setning enn et komponentnavn.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/kodeverk/koder.ts
> +export const JournalføringRolle = {
Rolle eller Aktør? Idk selv. Men spørsmål du kan tenke på.

2022-04-20 15:28 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +    .when("journalføresPå", {
Skulle man heller ha kalt det "journalføringsrolle" / "journalføringsaktør" i steden for "journalføresPå"?

2022-04-22 06:03 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
>  export const AvsenderOrganisasjon = ({
Det er laget en egen task: https://jira.adeo.no/browse/MELOSYS-5091

Tar skissene på ting som er nytt i denne tasken, men fokuserer ellers på funksjonalitet :D

2022-04-22 06:11 UTC, janitamarielle commented on src/sider/journalforing/journalforing.js
> +    const { navn = "" } = response.data;
Dette var mest for å få det konsekvent med hentOgVisBruker. Endrer til:
```
    const response = await sokOrgnr(virksomhetOrgnr);
    const navn = response?.data?.navn;
    if (Utils._isEmpty(navn)) {
      return false;
    }
```

2022-04-22 06:35 UTC, janitamarielle commented on src/kodeverk/koder.ts
> +export const JournalføringRolle = {
Tror aktør kan være misvisende mtp aktørId og at vi egentlig kun bruker det når det er snakk om bruker 🤔

2022-04-22 06:41 UTC, janitamarielle commented on src/sider/journalforing/journalforing.js
> +      virksomhetOrgnr: !journalføresPåBruker ? virksomhetOrgnr : null,
Hmm, det er mest fordi brukerID/virksomhetOrgnr blir resatt til "" og ikke null. Men kan se hvor lett det er å endre til null og da slippe denne.

2022-04-22 07:21 UTC, janitamarielle commented on src/sider/journalforing/journalforing.js
> +      virksomhetOrgnr: !journalføresPåBruker ? virksomhetOrgnr : null,
Fixed ✅

2022-04-22 10:27 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +  avsenderID: string().when(["avsenderType", "$erAvsenderPreutfylt", "journalføresPå"], {
Done

2022-04-22 10:28 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +    .when("journalføresPå", {
Hører med Mina. Skal grubles litt på 🤔 ⏳

2022-04-22 10:29 UTC, janitamarielle commented on src/sider/journalforing/komponenter/dokumentetJournalføresPå.tsx
> +const DokumentetJournalføresPå = ({ journalføresPå, oppdaterFelt, defaultBrukerID }: PropsFromRedux) => {
Skal endre når vi bestemmer oss for navn. Tenkte vi hadde gått for å bruker ÆØÅ, men dersom det skaper issues i git må vi jo unngå det.

2022-04-22 10:31 UTC, janitamarielle commented on src/sider/journalforing/komponenter/komponent.tsx
> +const Komponent = ({ ikon: Ikon, tittel, innhold }: KomponentProps) => {
Hmm, jeg kan det, men den er jo allerede innenfor journalforing-mappen. 
Blir kanskje mye duplisering og vanskelig å finne frem dersom alt skal ha prefiks journalføring? 

Denne komponenten er ment kun brukt for journalføring så man skal egentlig ikke randomly komme inn 🤔

2022-04-22 10:54 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +export const AvsenderFullmektig = ({
Kan kanskje lage en avsendere-folder under /komponenter og skille ut AvsenderOrganisasjon, AvsenderFullmektig og AvsenderUtenlandskTrygdemyndighet.

@martonSkjevelandNav Ødelegger det for deg dersom dette gjøres her?

2022-04-22 10:56 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendervelger.js
> +            {formValues.avsenderType === KV.AvsenderTyper.ARBEIDSGIVER && (
Løst i https://github.com/navikt/melosys-web/pull/1458/commits/a0dd426ccc62501802dc48703da6f0c7db0bd511. Var jeg som hadde glemt å legge til props i alle type avsendere 🙃

2022-04-27 10:03 UTC, frans-a commented on src/kodeverk/koder.ts
> +export const JournalføringRolle = {
Bør det defineres her? Alle konstanter er ikke nødvendigvis kodeverk, dette er ikke offisielt kodverk som https://kodeverk-web.dev.adeo.no eller https://confluence.adeo.no/display/TEESSI/Kodeverk+i+Melosys. Det kunne defineres nærmere journalføring tenkte jeg.

Disse konstanter definerer hvem gjelder forsendelsen og journalføringen. Det kunne kanskje kalles `JournalføringGjelder`? Både `JournalføringRolle` og aktør er utydelig for meg

2022-04-27 10:28 UTC, frans-a commented on src/sider/journalforing/komponenter/komponent.tsx
> +const Komponent = ({ ikon: Ikon, tittel, innhold }: KomponentProps) => {
Tenker litt som Janita her. Har vi ikke nok kontekst allerede Isa?
Samtidig kaller man f.eks. i api `FagsakService` selv om klassen finnes under pakken fagsak

2022-04-27 11:23 UTC, frans-a commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Dette ser ikke ut til å stemme. Hvis det journalføres på virksomhet blir fullmektig representant for virksomheten, ikke arbeidsgiver.

> det kun er mulig at fullmektig er fullmektig for "Virksomhet"

2022-04-27 11:33 UTC, frans-a commented on src/sider/journalforing/komponenter/dokumentetJournalføresPå.tsx
> +const DokumentetJournalføresPå = ({ journalføresPå, oppdaterFelt, defaultBrukerID }: PropsFromRedux) => {
Vi har brukt ÆØÅ i filer uten problemer, men i filnavn er det fortsatt problematisk og bør unngås

2022-04-28 10:28 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +    .when("journalføresPå", {
Vi prøver JournalføringGjelder

2022-04-28 13:41 UTC, janitamarielle commented on src/sider/journalforing/journalforing.js
> +    await hentFagsakListeForOrgnr(virksomhetOrgnr);
Skrev om nå. Syns det ble mye mer oversiktlig nå samtidig som man fikk ryddet opp i mye kode som ikke var i bruk

2022-04-29 08:11 UTC, janitamarielle commented on src/kodeverk/koder.ts
> +export const JournalføringRolle = {
Enig, disse kan legges i journalførings-komponenten 🤔 

Mina likte `JournalføringGjelder` så da går vi for den 👍

2022-04-29 08:20 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/journalforingSchema.js
> +    .when("journalføresPå", {
JournalføringGjelder hørtes bra ut

2022-04-29 08:20 UTC, IsaSalemHame commented on src/kodeverk/koder.ts
> +export const JournalføringRolle = {
JournalføringGjelder hørtes mer tydelig ut.

2022-05-02 00:31 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/komponent.tsx
> +const Komponent = ({ ikon: Ikon, tittel, innhold }: KomponentProps) => {
Delvis enig med dere, men i dette tilfellet er det omtrent 20 andre filer i mappen for "journalforing", og "komponent" er såpass generisk (og litt reservert) navn at det er misvisende hva det representerer.

Da jeg skrev den kommentaren trodde jeg at det var "hovedkomponenten" for journalføring. Når jeg ser nærmere på det, så er det egentlig et felt det representerer. In any case så mener jeg det er dårlig navn. 

Ved nærmere kikk så er jeg i tvil på om hele komponenten er i det hele tatt nødvendig. Det blir brukt ett sted, og gjør ikke at man sparer kode elns.

2022-05-02 00:32 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/komponent.tsx
> +      {innhold}
Vet ikke hva som er standard i React/hva som er best practices når det er ett child element, men kunne kanksje ha hatt {props.content} her, og ellers `<Komponent ...> <innholdet/> </Komponent>` når vi skal bruke den.

2022-05-02 00:34 UTC, IsaSalemHame commented on src/sider/journalforing/journalforing.js
> +    await hentFagsakListeForOrgnr(virksomhetOrgnr);
nice

2022-05-02 06:07 UTC, janitamarielle commented on src/sider/journalforing/komponenter/komponent.tsx
> +const Komponent = ({ ikon: Ikon, tittel, innhold }: KomponentProps) => {
> Ved nærmere kikk så er jeg i tvil på om hele komponenten er i det hele tatt nødvendig. Det blir brukt ett sted, og gjør ikke at man sparer kode elns.

Vet ikke om det kom frem godt nok, men denne er tenkt brukt i alle delene/komponentene i journalføringsbildet siden det er nye skisser på journalføring. Siden det blir for mye å ta all styling/skisse-endring nå er det laget egen jira-sak på det.

2022-05-02 06:56 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +export const AvsenderFullmektig = ({
Ser ut som marton har fiksa i https://github.com/navikt/melosys-web/pull/1484/files 👏

2022-05-02 10:39 UTC, janitamarielle commented on src/sider/journalforing/komponenter/komponent.tsx
> +      {innhold}
Her har jeg egentlig bare brukt det vi ellers har i prosjektet 🤔 Kan se hvordan det blir seende ut?

2022-05-02 11:15 UTC, IsaSalemHame reviewed
Veldig godt jobbet!

2022-05-02 11:15 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/journalforingSchema.js
>  const journalforing = object().shape({
Ser ut som journalføringsknappen ikke lenger gjør noe

2022-05-02 11:15 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/avsendervelger.js
> +        kopierVirksomhetTilAvsender();
Hva er det denne gjør egentlig? Tømmer avsender/org.navn elns?

2022-05-02 11:43 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendervelger.js
> +        kopierVirksomhetTilAvsender();
Denne setter vel avsender id og navn til virksomhet id og navn.

2022-05-02 11:49 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Hmm, dette stemmer. Den representerer jo virksomheten, som i dette tilfellet er BRUKER... 🤔 

Skal vi fortsette med representerer-kode eller potensielt rename den BRUKER_ELLER_VIRKSOMHET? Vil tro det er generelt samme oppførsel på BRUKER og VIRKSOMHET i dette tilfellet, og at man derfor ikke trenger en helt ny kode. Men her er jeg usikker.

2022-05-02 11:49 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingSchema.js
>  const journalforing = object().shape({
Skal sjekke. Vet jeg har gjort endringer i skjema uten lokaltesting

2022-05-02 12:20 UTC, frans-a commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
:warning: bruker i Melosys-kontekst er ikke det samme som bruker i Joark-kontekst.
Bruker i Melosys betyr personen vi prøver å avklare lovvalg og trygdetilhørighet for.
Mens bruker hos Joark betyr bare hvem gjelder dokumentet som skal journalføres.

Så siden representant er i Melosys-kontekst blir det en forskjell om vi lagrer representant som representerer en person (bruker) i stedet for fullmektig.

Se https://github.com/navikt/melosys-api/pull/1122#issuecomment-1114775530

2022-05-02 12:31 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Enig i at vi ikke kan bruke Representerer.BRUKER. Spørsmålet er om vi skal lage ny Representerer.VIRKSOMHET eller om vi skal rename Representerer.BRUKER_ELLER_VIRKSOMHET 🤔 

Det kommer jo an på om melosys skal behandle dem forskjellig.

2022-05-02 12:50 UTC, frans-a commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Representerer.BRUKER brukes allerede, ja, og kan ikke ikke bety at virksomhet representeres.
Jeg ser ikke helt hvordan BRUKER_ELLER_VIRKSOMHET skulle fungere.
Om man representerer ARBEIDSGIVER eller VIRKSOMHET er det ikke nødvendigvis det samme.

2022-05-02 12:56 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingSchema.js
>  const journalforing = object().shape({
El problemo: https://github.com/navikt/melosys-web/pull/1458/commits/98b026cda43e06c0ee25923133144e10a8ce4ced

2022-05-02 12:57 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/journalforingSchema.js
>  const journalforing = object().shape({
olala :smirk:

2022-05-02 13:03 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Hmm, for nå har vi BRUKER, ARBEIDSGIVER, og BEGGE i kodeverket "representerer". 

Til nå har det betydd at skal bruker ha brev sender man det til den fullmektige for bruker. 
Det vil vel være tilsvarende logikk for fullmektig for virksomhet: Dersom virksomheten skal ha brev sender man det istedenfor til den fullmektige. 
Syns altså at det er lik logikk for fullmektig som representerer BRUKER og en mulig ny VIRKSOMHET-kode. Hvorfor ikke da sette BRUKER til BRUKER_ELLER_VIRKSOMHET dersom logikken kommer til å være den samme?

Bruker har frem til nå vært den man journalfører på, eller den nye journalføringenGjelder-feltet. Man er altså fullmektig for den journalføringen gjelder. Som nå kan være BRUKER eller VIRKSOMHET.

2022-05-02 13:03 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
Skal jeg kalle inn møte med Yvonne (og Mina) om dette?

2022-05-02 13:19 UTC, janitamarielle commented on src/sider/journalforing/komponenter/komponent.tsx
> +      {innhold}
On 2. thought, tar gjerne å skipper denne dersom du ikke brenner for det.

2022-05-02 13:24 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/komponent.tsx
> +      {innhold}
Brenner ikke for det.

2022-05-02 13:25 UTC, IsaSalemHame commented on src/sider/journalforing/komponenter/komponent.tsx
> +      {innhold}
![image](https://user-images.githubusercontent.com/7471428/166241101-31a05cd8-6825-4086-9f47-7ece510a3c6a.png)

2022-05-03 07:29 UTC, janitamarielle commented on src/sider/journalforing/komponenter/informasjon.js
> +        </>
Det kommer nok i skisse-saken nevnt tidligere.

2022-05-03 11:44 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
https://confluence.adeo.no/display/TEESSI/Kodeverk+i+Melosys#KodeverkiMelosys-Akt%C3%B8rsrollerogRepresenterer

~~Lager ny kode i kodeverket.~~ 
Nope, leste feil - så på aktør. Spør i melosys-fag.

2022-05-04 10:07 UTC, janitamarielle commented on src/sider/journalforing/komponenter/avsendere.js
> +      settFeltInnhold("representantRepresenterer", MKV.Koder.representerer.ARBEIDSGIVER);
[Vi skal ikke støtte fullmektig for virksomhet](https://github.com/navikt/melosys-api/pull/1122#issuecomment-1117139034)

2022-05-05 10:28 UTC, janitamarielle commented
Merk at jeg revertet de fleste endringene på avsender-domenet her. Halvveis på grunn av at VIRKSOMHET skal ha default avsender så man viser ikke disse lengre, og halvveis fordi den oppryddingen jeg har gjort også kommer i PR-en: https://github.com/navikt/melosys-web/pull/1484

2022-05-05 10:46 UTC, IsaSalemHame approved these changes
Very nice

2022-05-09 05:44 UTC, janitamarielle commented
Ble ganske store endringer etter merge inn master, greit å få andre enn mine øyne på det 😄

2022-05-09 08:31 UTC, IsaSalemHame approved these changes
Har testet med kombinasjonene jeg kan komme på, og det ser ut til å funke som det skal. 
Det er to ting jeg la merke til, men som ikke har så mye med det du har gjort å gjøre. Nummer 2 er noe som kaaanskje bør gjøres her? Du kan sjekke og avgjøre hvor kritisk det er.

1. Etter å ha journalført kommer ikke navnet på organisasjonen opp på forsiden i oppgavelisten. Blir feks "Trygdeavtale - null - null". Bør fikses i egen oppgave, ettersom det involverer både frontend og backend.
2. Journalføring-knappen er tilgjengelig selv om man ikke har oppgitt orgnr/persnr.

2022-05-09 09:56 UTC, janitamarielle commented
> 1. Etter å ha journalført kommer ikke navnet på organisasjonen opp på forsiden i oppgavelisten. Blir feks "Trygdeavtale - null - null". Bør fikses i egen oppgave, ettersom det involverer både frontend og backend.

Mina har avklart. Det kommer i egen oppgave med andre endringer som må justeres for virksomhet. 

> 2. Journalføring-knappen er tilgjengelig selv om man ikke har oppgitt orgnr/persnr.

Knapp skal være tilgjengelig, men nå kommer feilmeldingen opp sammen med de andre når du trykker på den: https://github.com/navikt/melosys-web/pull/1458/commits/5b6eff84bb9796c8fd2cea7333722fb0a5a9bfa0

2022-05-09 11:24 UTC, merged