MELOSYS-4747: Frontend sjekker om vi kan godkjenne A009 saker med et spesifikt tema.
navikt/melosys-web pull request #1511
Opened 2022-06-16 07:00 UTC by ivanskodje

Ref: https://jira.adeo.no/browse/MELOSYS-4747

* Lagt til ny kontroller API for å sjekke om vi skal kunne godkjenne unntaksperiode

* Vi bruker samme feilhåndteringslogikk som ved andre kontroll, så hvis vi får feil (uansett årsak, som vi kan velge å vise eller fremheve hvis vi ønsker) så skal vi ikke vise godkjenn knappene

* Hovedendring er gjort i saksopplysninger.js, der vi nå disabler knappen hvis vi får en sak som ikke skal kunne godkjennes manuelt for unntak

(Stor takk til Marton)

----

2022-06-16 10:16 UTC, janitamarielle commented
Fikser du package-lock? Du har mest sannsynlig feil versjon av npm 🤔

2022-06-16 10:18 UTC, janitamarielle commented on src/services/modules/kontroll.ts
> +export const kontrollerGodkjennUnntaksperiode = (behandlingID: number) =>
sendes ikke `behandlingID` som body nå? Vi vil vel heller ha det som query-param?

2022-06-16 10:20 UTC, janitamarielle commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    kontrollerGodkjennUnntaksperiode(behandlingID);
Det ser ut som du her direkte bruker `kontrollerGodkjennUnntaksperiode` istedenfor å hente funksjonen fra props. Legg `kontrollerGodkjennUnntaksperiode` på props tilsvarende `kontrollFeilmeldinger` (linje 49) og slett unødvendig import deretter.

2022-06-16 10:22 UTC, janitamarielle commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const kanGodkjenne = () => !(kontrollFeilmeldinger && kontrollFeilmeldinger.length > 0);
Blir denne feil når kontrollFeilmeldinger er undefined? **!(undefined) = true**

`!(kontrollFeilmeldinger && kontrollFeilmeldinger.length > 0)` => `kontrollFeilmeldinger?.length === 0`?

2022-06-17 07:18 UTC, ivanskodje commented on src/services/modules/kontroll.ts
> +export const kontrollerGodkjennUnntaksperiode = (behandlingID: number) =>
:heavy_check_mark:

2022-06-17 07:20 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    kontrollerGodkjennUnntaksperiode(behandlingID);
Det var lurt !

2022-06-17 07:24 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const kanGodkjenne = () => !(kontrollFeilmeldinger && kontrollFeilmeldinger.length > 0);
Det burde ikke være et problem / mulig, ved mindre dette også er et feil andre steder som f.eks. `dialogboksHenlegg.tsx`. Kan det være tilfellet?  Evt. kan vi se på hvilken måte vi ønsker å bruke fremover? :) 

Jeg ser at noen steder har vi bare brukt `Utils._isEmpty(feilmeldinger)`, tror du det holder å bruke dette?

```
const kanGodkjenne = () => Utils._isEmpty(feilmeldinger);
```

(derimot bør vi refaktorere isEmpty til å ikke bruke _, ettersom det vanligvis betyr at det er en "privat" funksjon som ikke skal brukes utenfra... kanskje noen som har tatt snarveier :thinking:  )

2022-06-17 09:39 UTC, janitamarielle commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const kanGodkjenne = () => !(kontrollFeilmeldinger && kontrollFeilmeldinger.length > 0);
Du kan git blame på Utilsmappen tror jeg for å finne forklaring på remaningen til _. Mener det var god begrunnelse uten at jeg husker den nå.

Men ja jeg syns du absolutt kan endre til Utils._isEmpty(). Syns det er veldig klart hva som gjør at det kanGodkjennes. Det har vært litt diskusjon om isEmpty er overkill noen steder, men her sjekker man jo om det er undefined/null og om det er tom liste så syns det går bra.

2022-06-17 09:45 UTC, janitamarielle commented on src/services/modules/kontroll.ts
> +  behandlingID: number;
Kan hende vi snakket forbi hverandre, men mente at vi vil ha behandling som queryparam og ikke som body. Det er slik det er gjort ellers i prosjektet. 

Ex: 
```
export const send = (behandlingID, data) =>
  postAsJson(`${API_BASE_URL}${REGISTRERING}/${behandlingID}/unntaksperioder`, data);
```

2022-06-17 09:49 UTC, janitamarielle commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    console.log("Behandling ID:");
Husk å fjerne disse

2022-06-21 06:18 UTC, ivanskodje commented
@janitamarielle Har manuelt endret package-lock til å være lik master

2022-07-19 07:03 UTC, janitamarielle commented
Refererer til samtale på slack:
> Tror ikke vi trenger to kontroll-endepunkt for dette :thinking_face:
Heller bruke ett endepunkt, som både kalles ved start og ved endring av perioder. Som sender med periode hele tiden. Så ved start er perioden lik det som er i backend, men etterhvert som saksbehandler endrer det så blir de ulike.
Evt, har du vurdert det å lagre perioden i backend før du gjør kontrollen? Slik at godkjennunntaksperiode-kontrollen går mot de dataene saksbehandler ser?

2022-07-27 09:23 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harUnntaksperiodefeil = () => !Utils._isEmpty(unntaksperiodeFeilmeldinger);
Siden denne sjekker kun om unntaksperiodeFeilmeldinger er empty, så trenger den ikke å være en funksjon. Foreslår: `const harUnntaksperiodefeil = !Utils._isEmpty(unntaksperiodeFeilmeldinger);`

2022-07-27 09:24 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering;
Denne trenger heller ikke være en funksjon. Da slipper du å kalle `harValgtIkkeGodkjenn()`, kan da skrive `harValgtIkkeGodkjenn`

2022-07-27 09:30 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const kanIkkeGodkjenneUnntaksperiodeUtenEndringAvPerioden = () => {
Ser lengre nede i koden at den brukes til å sjekke for disabled. Det blir litt rart mtp. at den også har logikk inne i seg som setter state. 

Tror det beste her er å skrive om denne litt, slik at den gjør kun det den skal. Siden den heter `kanIkkeGodkjenneUnntaksperiodeUtenEndringAvPerioden` og den brukes for å sjekke disabled, forventer jeg som leser denne koden at den returnerer true/false og ikke er en funksjon.

Foreslår å splitte ut denne, slik sånn ca: 

```
const harIkkeForsøktEndrePeriode = !endrePeriodeTom && !endrePeriodeFom;
const harFeilEtterFørsteSjekk = harIkkeForsøktEndrePeriode && !kanIkkeGodkjenneUnntaksperiodeUtenEndring && harUnntaksperiodefeil;
```

Dermed bruke den i disabled slik: 
`                      disabled={(harIkkeForsøktEndrePeriode && harFeilEtterFørsteSjekk) || !erGyldigLovvalgsperiode()}
`
Noe lignende sånn tenker jeg er bedre lesbart

2022-07-27 09:32 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +                      disabled={kanIkkeGodkjenneUnntaksperiodeUtenEndringAvPerioden() || !erGyldigLovvalgsperiode()}
Se kommentarene over

2022-07-27 09:33 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +                      disabled: !harValgtIkkeGodkjenn() && (!redigerbart || harUnntaksperiodefeil()),
Se kommentarene over

2022-07-27 09:33 UTC, thanglyphan requested changes
Kommenterte litt på koden

2022-07-27 09:37 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harUnntaksperiodefeil = () => !Utils._isEmpty(unntaksperiodeFeilmeldinger);
Men lagrer den ikke verdien bare én gang? 
Vi ønsker å sjekke hver gang (altså ikke cache verdien slik at den ikke kjøres flere ganger)

2022-07-27 09:38 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering;
Samme spørsmål til denne som forrige

2022-07-27 09:41 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const kanIkkeGodkjenneUnntaksperiodeUtenEndringAvPerioden = () => {
Samme spørsmål som de andre. Vi kan vel ikke sette dette én gang i en variabel, og forvente at den endrer seg? 

Derimot liker jeg forslaget med å dele de opp (venter med å gjøre noe før jeg får svar ang. variabelen)

2022-07-27 09:46 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering;
Ok, jeg tok en nærmere titt på denne   `const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering`, hvor unntaksperiodeVurdering er en state. Hvis du vil at denne `harValgtIkkeGodkjenn` skal endres når `unntaksperiodeVurdering` endrer seg, er det best å gjøre det med useEffect slik:

`const [harValgtIkkeGodkjenn, setHarValgtIkkeGodkjenn] = React.useState(false)` 

```
React.useEffect(() => {
   setHarValgtIkkeGodkjenn(KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering)
  }, [unntaksperiodeVurdering]);
```

Da er `harValgtIkkeGodkjenn` alltid oppdatert og man kan sjekke hver gang

2022-07-27 09:47 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harUnntaksperiodefeil = () => !Utils._isEmpty(unntaksperiodeFeilmeldinger);
Ga et mer utfyllende svar under

2022-07-27 09:49 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering;
Det er på denne måten vi kan ha kontroll over hva som endres og når, ved hjelp av useEffect

2022-07-27 09:51 UTC, thanglyphan requested changes
Kommenterte på kommentar

2022-07-27 09:55 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  const harValgtIkkeGodkjenn = () => KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering;
```
const [harUnntaksperiodefeil, setHarUnntaksperiodefeil] = React.useState(false)
const [harValgtIkkeGodkjenn, setHarValgtIkkeGodkjenn] = React.useState(false)

React.useEffect(() => {
   setHarUnntaksperiodefeil(!Utils._isEmpty(unntaksperiodeFeilmeldinger))
   setHarValgtIkkeGodkjenn(KV.Koder.Unntaksperiode.AVSLAG === unntaksperiodeVurdering)
}, [unntaksperiodeVurdering, unntaksperiodeFeilmeldinger]);
```

Blir det for de to, da er de alltid oppdatert og enklere å holde det oppdatert

2022-07-27 10:35 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Putt denne variabelen sammen med de andre i useEffect: `[...kanIkkeGodkjenneUtenÅEndrePerioden]` ellers vil den ikke lytte

2022-07-27 10:35 UTC, thanglyphan requested changes
Det så mye bedre og mer oversiktlig ut, en liten ting til :)

2022-07-27 10:39 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Forstår ikke hva du mener. Denne skal bare kjøres én gang (setKanIkkeGodkjenneUtenÅEndrePerioden). Denne skal hindre at man kan godkjenne uten å måtte tvinges til å endre perioden.

Har testet manuelt, og denne fungerer som forventet

2022-07-27 10:45 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Akkurat nå vil denne if sjekken sjekke hver gang `unntaksperiodeVurdering, unntaksperiodeFeilmeldinger, harUnntaksperiodefeil`. Hvis du skal ha denne til å sjekke kun en gang, må den ut av useEffect. Ser også at `endrePeriodeTom, endrePeriodeFom` brukes her inne, de må også være med sammen med de andre states'ene under.

F.eks. Du endrer verdien i endrePeriodeTom. Denne useEffecten vil ikke få den nye verdien til endrePeriodeTom, den kjører kun når en av disse verdiene endrer seg `[unntaksperiodeVurdering, unntaksperiodeFeilmeldinger, harUnntaksperiodefeil]`.

2022-07-27 10:47 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Denne her kan heller ikke være med i useEffect [] - `harUnntaksperiodefeil`. Den kan skape en evig loop for nå lytter du på `harUnntaksperiodefeil` mens du setter ny verdi på den.

2022-07-27 10:50 UTC, thanglyphan requested changes
:)

2022-07-27 10:52 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Hvis du vil at den skal sjekke on mount f.eks. kan du bruke useEffect med en tom [].

2022-07-27 10:56 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Det er fordi jeg må vente til vi får harUnntaksperiodefeil første gangen før vi sjekker. Den må altså være inni useEffect fordi vi vet ikke når vi får harUnntaksperiodefeil.

 Kanskje jeg kunne lage enda en useEffect og bare sjekke [harUnntaksperiodeFeil] slik at vi sjekker den bare når den settes?

Vi ønsker ikke å sjekke denne når endrePeriodeTom/Fom endrer seg.

2022-07-27 10:57 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Denne her høres veldig bra ut :) 

Kanskje jeg kunne lage enda en useEffect og bare sjekke [harUnntaksperiodeFeil] slik at vi sjekker den bare når den settes?

2022-07-27 10:58 UTC, thanglyphan requested changes
Kommentar

2022-07-27 11:18 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +    if (!kanIkkeGodkjenneUtenÅEndrePerioden) {
Done

2022-07-27 11:20 UTC, thanglyphan commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  }, [unntaksperiodeVurdering, unntaksperiodeFeilmeldinger, harUnntaksperiodefeil]);
`harUnntaksperiodefeil` - kan fjernes, ser ikke ut til at denne brukes.

2022-07-27 11:24 UTC, thanglyphan requested changes
Ser bra ut, liten state håndtering til

2022-07-27 11:55 UTC, ivanskodje commented on src/sider/eu_eøs/registrering/unntaksperioder/saksopplysninger.js
> +  }, [unntaksperiodeVurdering, unntaksperiodeFeilmeldinger, harUnntaksperiodefeil]);
Nice catch, rask iterasjoner!

2022-07-27 11:57 UTC, thanglyphan approved these changes

2022-07-27 18:22 UTC, merged