5195 FAG DAPI TOGGLE Vise sakstema og behandlingsresultattype i saksoversikten
navikt/melosys-web pull request #1543
Opened 2022-08-11 06:27 UTC by janitamarielle

Vise sakstema og behandlingsresultattype i saksoversikten. Det er også blitt litt skisse-endringer.
Merk at endringer i sorterbarListe.js og soknadsland.tsx kommer fra https://github.com/navikt/melosys-web/pull/1542

Avhengig av melosys-api: https://github.com/navikt/melosys-api/pull/1317 (**MERGED**)

Jira: https://jira.adeo.no/browse/MELOSYS-5195

Skisser: https://www.figma.com/file/WoveeUX7SM2KNAjGHjGf75/Arbeidsbenk-og-saksoversikt?node-id=4135%3A10340

2022-08-11 07:22 UTC, IsaSalemHame commented
Kudos for ryddig PR-beskrivelse!

2022-08-11 10:30 UTC, IsaSalemHame requested changes

2022-08-11 10:30 UTC, IsaSalemHame commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
Den linjen bør gjøres lengre. Bryter opp alt for tidlig nå:
![image](https://user-images.githubusercontent.com/7471428/184114321-0de66168-3d8a-491b-8344-7718b21acf23.png)

2022-08-11 10:32 UTC, janitamarielle commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
Lol dette testet jeg jo. Skal se på det

2022-08-11 10:35 UTC, IsaSalemHame commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                <Behandlingsstatuskode behandlingsstatus={behandlingsstatus} />
Ikke denne PR'en, men låseikonen og teksten burde ha litt mer spacing. Litt for tett på hverandre nå.

2022-08-11 10:37 UTC, IsaSalemHame commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
Uh, funka plutselig etter refresh :confused:

2022-08-11 10:38 UTC, IsaSalemHame commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
aah. Fant feilen!

Når man _søker_ og kommer seg inn i lista, så blir det sånn. Etter refresh funker det.

2022-08-11 10:47 UTC, janitamarielle commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
Huh, det er mystisk. Tror jeg uansett skal ta en titt for å se om jeg finner noe der 👀

2022-08-11 12:34 UTC, janitamarielle commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                    {behandlingsresultattype.term}
Fant det 🎉

2022-08-11 12:35 UTC, janitamarielle commented on src/felleskomponenter/oppgaveliste/behandling.js
> +                <Behandlingsstatuskode behandlingsstatus={behandlingsstatus} />
Yeah. Ser den ikke har egen styling, så tar en mini-PR etter alle 3 PR-ene er ute for å rydde litt opp i det.

2022-08-11 13:32 UTC, IsaSalemHame reviewed
Hvorfor blir land ukjent når det er to behandlinger på én sak? Hvis det _alltid_ er ukjent hvis det er flere behandlinger, burde kanskje land være skjult?

2022-08-11 13:34 UTC, janitamarielle commented
> Hvorfor blir land ukjent når det er to behandlinger på én sak?

Man viser vel landet til den nyeste? Ellernoe logikk i bakgrunnen. Skal ikke ha vært rørt på i denne PR-en .... i think

2022-08-12 08:45 UTC, IsaSalemHame commented
> Man viser vel landet til den nyeste? Ellernoe logikk i bakgrunnen. Skal ikke ha vært rørt på i denne PR-en .... i think

Klarte ikke gjenskape det of some reason :|

2022-08-12 08:47 UTC, IsaSalemHame approved these changes
:1st_place_medal:

2022-08-13 05:10 UTC, merged