4828 Toggle Fritekstvedlegg i fritekstbrev
navikt/melosys-web pull request #1581
Opened 2022-09-15 14:16 UTC by fredrik-oh

https://jira.adeo.no/browse/MELOSYS-4828

Dependent PRs:
https://github.com/navikt/melosys-web/pull/1581
https://github.com/navikt/melosys-dokgen/pull/191

2022-09-20 12:57 UTC, IsaSalemHame requested changes

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/brevVedlegg.tsx
> +  slettFritekstvedlegg: (index: number) => void;
Note4myself. Hva er index her?

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/fritekstvedleggSkjema.tsx
> +        <Nav.Row>
Skulle man hatt en "Forhåndsvis"-knapp også? Da slipper man å lagre, for så å forhåndsvise. Vet ikke hvor stort behov det vil være for det, men...
I hovedbrevet kan man alltids forhåndsvise, selv om man ikke er ferdig med å skrive.. 

En annen løsning kan være å ikke slette raden fra vedlegglista når man redigerer? Idk. Igjen, jeg vet ikke om hvor stort behov det er.

![image](https://user-images.githubusercontent.com/7471428/191250807-c1899f74-52f3-4c57-a906-29e136ac436b.png)

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggvelger/vedleggTable.tsx
> +            index={index}
Vi har ikke et bedre navn enn "index"?

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggvelger/fritekstvedleggRow.tsx
> +          onClick={() => redigerFritekstvedlegg && redigerFritekstvedlegg(index)}
Bug: Hvis du har to vedlegg, prøver å redigere den ene, for så å trykke rediger på neste også, så slettes ene vedlegget.

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/sendBrev.tsx
> +      {fritekstvedleggFelt &&
Noe føles rart her... 
Ene er at det er to like knapper, men i to forskjellige komponenter: `Legg til vedlegg` og `Legg til fritekstvedlegg`. 
Slik det er nå, er i tillegg FritekstvedleggSkjema avhengig av BrevVedlegg på grunn av listen over fritekstvedlegg som har blitt lagt til. I en rar verden med en brevtype i backend der man har fritekstvedlegg, men ikke vedlegg, vil man altså ikke kunne se vedlegget man har lagt på. 
Foreslår at tabellen over vedlegg som har blitt valgt/lagt til kommer seg ut på en eller annen måte så Fritekstvedlegg ikke er avhengig av BrevVedlegg. Eventuelt kan du flette fritekstvedleggFelt inn i BrevVedlegg.

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggvelger/__snapshots__/slettFritekstvedleggModal.test.tsx.snap
> +      className="lukknapp lukknapp--overstHjorne modal__lukkknapp--shake"
kkk

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggvelger/slettFritekstvedleggModal.tsx
> +      // @ts-ignore
Jeg fikk ikke noe fel uten `@ts-ignore` :O

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/fritekstvedleggSkjema.tsx
> +            Avbryt
Bug: Hvis du lagrer fritekstvedlegg, redigerer og trykker Avbryt, så slettes hele fritekstvedlegget.

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/sendBrev.tsx
> +      // TODO: Feilhåndtering
TODO

2022-09-20 12:57 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/brevVedlegg.tsx
> +  lagPdfUrl: (index: number) => Promise<string | false>;
Ser ut som det bare blir brukt ifm. fritekstvedleggvisning? I så fall kall det noe annet. Kanskje lagFritekstPdfUrl, som du allerede har kalt det et annet sted.

2022-09-20 13:01 UTC, fredrik-oh commented on src/felleskomponenter/sideDialog/sendBrev/sendBrev.tsx
> +      // TODO: Feilhåndtering
Skulle vært notification fra github når du prøver å opprette en PR med todo kommentarer i endringssettet 😅

2022-09-20 13:06 UTC, fredrik-oh commented on src/felleskomponenter/sideDialog/sendBrev/brevVedlegg.tsx
> +  slettFritekstvedlegg: (index: number) => void;
array index på fritekstvedlegg som ligger i sendbrev state

2022-09-20 13:08 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/brevVedlegg.tsx
> +  slettFritekstvedlegg: (index: number) => void;
ja, skjønte det etterpå. glemte å fjerne kommentar. index høres så vagt ut hvis man ikke har en klar oversikt over hvordan ting henger sammen. Men samtidig har jeg ikke så mye bedre forslag :( Kunne kanskje ha funnet brev basert på tittel, men det er fort gjort å ha to like titler..

2022-09-20 13:08 UTC, fredrik-oh commented on src/felleskomponenter/sideDialog/sendBrev/fritekstvedleggSkjema.tsx
> +        <Nav.Row>
Tror jeg går for å ikke fjerne vedlegget fra listen når vi redigerer

2022-09-20 13:09 UTC, fredrik-oh commented on src/felleskomponenter/vedleggvelger/fritekstvedleggRow.tsx
> +          onClick={() => redigerFritekstvedlegg && redigerFritekstvedlegg(index)}
Fikser dette ved å ikke fjerne vedlegget fra listen når vi redigerer

2022-09-26 07:46 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/sendBrev.tsx
> +      // TODO: Feilhåndtering
tror du kan få intellij til å varsle deg

2022-10-04 10:26 UTC, barstadEkstern approved these changes
Ser ikke noe spesielt utover det som er nemnt. La inn en liten kommentar som kanskje kan fikses om du synest det gir mening.

2022-10-04 10:26 UTC, barstadEkstern commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +      {(valgteVedlegg.length > 0 || (fritekstvedlegg && fritekstvedlegg.length > 0)) && (
Burde vi sjekke valgteVedlegg også før vi sjekker lengden?

2022-10-04 14:38 UTC, fredrik-oh commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +      {(valgteVedlegg.length > 0 || (fritekstvedlegg && fritekstvedlegg.length > 0)) && (
Sjekker om fritekstvedlegg er definert siden det er en optional param

2022-10-05 08:24 UTC, IsaSalemHame approved these changes
Ser bra ut! Fiks testene som feiler, så er det good.

2022-10-05 08:24 UTC, IsaSalemHame commented on src/felleskomponenter/sideDialog/sendBrev/sendBrev.tsx
> +          redigerFritekstvedlegg={redigerFritekstvedlegg}
Det er sikkert ikke nødvendig for denne omgang, men hadde vært fint å få det på plass en eller annen gang. Når man redigerer et fritekstvedlegg, for så å trykke på Rediger på en annen så burde bruker få varsel om at fritekstvedlegget som allerede var i redigeringsmodus ikke var blitt lagret og spørre om hen faktisk vil fortsette.

2022-10-05 08:24 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +                  slettFritekstvedlegg={slettFritekstvedlegg}
Ved sletting av fritekstvedlegg bør også redigeringsboksen bli lukket, dersom den er åpen for samme vedlegg som man sletter. Nå fører det til en liten bug hvis man gjør det på riktig index.

2022-10-05 08:24 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +                  key={vedlegg.tittel}
Key må være unik, tittel er ikke det. key=index?

2022-10-05 08:25 UTC, IsaSalemHame commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +                  slettFritekstvedlegg={slettFritekstvedlegg}
(gammel kommentar fra i går som kom inn med reviewen)

2022-10-05 13:30 UTC, fredrik-oh commented on src/felleskomponenter/vedleggTable/vedleggTable.tsx
> +                  key={vedlegg.tittel}
index gir warning og eslint feil mener jeg :(

2022-10-06 07:14 UTC, IsaSalemHame approved these changes
:100:

2022-10-06 09:37 UTC, merged