5199 Valideringer i opprett ny sak
navikt/melosys-web pull request #1666
Opened 2022-10-26 05:10 UTC by janitamarielle

La til valideringer for opprett ny sak, tilsvarende journalføringen. Laget også samme visning av disse.
La til hjelpefunksjon nullstillFelt.
Trakk ut mapping av data som var spesifikt for opprett ny sak (og ikke opprett behandling). 
Satte feilmeldingene som var felles for journalføring og opprettnysak i filen feilmeldinger i /kodeverk. 
Slettet gammel endepunkt som ikke finnes i backend lengre.

https://jira.adeo.no/browse/MELOSYS-5199

2022-10-26 05:11 UTC, janitamarielle commented
Snikstartet litt på 5199 ved å se på kommentarer om valideringer som var ønsket. Resterende tok jeg å gjorde om til tilsvarende journalføring.

Vurderer å dra ut logikken og koden for bruker/virksomhet/hovedpart for å få en litt mer oversiktlig fil... 🤔

2022-10-26 05:21 UTC, janitamarielle commented on src/sider/journalforing/komponenter/opprettSak.js
> +  sakstema &&
@martonSkjevelandNav 
Enig med denne?

2022-10-26 07:40 UTC, martonSkjevelandNav commented on src/sider/journalforing/komponenter/opprettSak.js
> +  sakstema &&
Ye 👍

2022-10-26 09:33 UTC, thanglyphan commented on src/sider/opprettnysak/opprettnysak.tsx
> +  const [knappTrykketPå, setKnappTrykketPå] = useState(false);
Hvis den kun brukes for å vise feilmelding, kan den hete noe som visFeilmelding og settes i .finally()

2022-10-26 09:35 UTC, thanglyphan commented on src/sider/opprettnysak/opprettnysak.tsx
> +      lagNySak(dataForOpprettSak(fellesData)).finally(() => setBekreftPending(false));
setKnappTrykketPå(true); // rename ? 

her nede? Spiller egt ikke så stor rolle

2022-10-26 09:35 UTC, janitamarielle commented on src/sider/opprettnysak/opprettnysak.tsx
> +  const [knappTrykketPå, setKnappTrykketPå] = useState(false);
Hmm kan sette til visFeilmelding, men blir kanskje litt misvisende å sette setVisFeilmelding(true) når det ikke er sikkert at det finnes feilmeldinger?

Nei, vi vil at det skal vises dersom det er feil også, så da kommer vi ikke til .finally()

2022-10-26 09:36 UTC, janitamarielle commented on src/sider/opprettnysak/opprettnysak.tsx
> +      lagNySak(dataForOpprettSak(fellesData)).finally(() => setBekreftPending(false));
> Nei, vi vil at det skal vises dersom det er feil også, så da kommer vi ikke til .finally()

Den må være true også når man return ut av funksjonen fordi det finnes errors

2022-10-26 09:41 UTC, thanglyphan requested changes
<img width="649" alt="image" src="https://user-images.githubusercontent.com/10921090/197992691-fa4ecaeb-4be3-47a6-a5dc-ae6a106356bc.png">

Velger alle typer sakstema osv. går tilbake og switcher BRUKER -> VIRKSOMHET -> BRUKER:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/10921090/197992895-dbe47d0a-8ef2-48c2-a872-925e2e7e32cc.png">

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10921090/197992963-037363f1-34be-4845-b7fc-71721c3167d5.png">

Må kanskje resette noe feilmeldinger her

2022-10-26 09:42 UTC, thanglyphan commented on src/sider/opprettnysak/opprettnysak.tsx
> +  const [knappTrykketPå, setKnappTrykketPå] = useState(false);
Ja, riktig, jeg overså den, sory

_Hmm kan sette til visFeilmelding, men blir kanskje litt misvisende å sette setVisFeilmelding(true) når det ikke er sikkert at det finnes feilmeldinger?_ - Neida, tror det er fint

2022-10-26 09:48 UTC, thanglyphan commented on src/sider/opprettnysak/komponenter/oppgaveVelger.tsx
> -  nullstillFormverdier,
Denne er vel grei å ha når du skal nullstille ting?

2022-10-26 09:50 UTC, thanglyphan commented on src/sider/opprettnysak/komponenter/oppgaveVelger.tsx
> +              change("oppgaveID", null);
Bruk nullstillFelt som du lagde i opprettnysak.tsx

2022-10-26 10:52 UTC, janitamarielle commented on src/sider/opprettnysak/komponenter/oppgaveVelger.tsx
> -  nullstillFormverdier,
Den resatte kun oppgaveID, og siden den uansett hadde change som et parameter, så bruker jeg heller change begge stedene. Da er det også mer åpenbart hva som skjer.

2022-10-26 10:53 UTC, janitamarielle commented on src/sider/opprettnysak/komponenter/oppgaveVelger.tsx
> +              change("oppgaveID", null);
https://github.com/navikt/melosys-web/pull/1666/files/4c609d0f2a1ee52aa2d0843e47bb939181d66d7e#r1005527585

Blir kun brukt én gang. Ser da ikke grunn til å sende med den også når `change("oppgaveID", null)` allerede er ganske lettleselig.

2022-10-26 11:08 UTC, janitamarielle commented
> Må kanskje resette noe feilmeldinger her

Hører med Cathrin. Vi har hatt samme diskusjon på journalføring. Tror vi kom frem til at vi ikke må ha det perfekt her, siden det er veldig ulogisk å prøve å journalføre på bruker før du så bytter til virksomhet. Men skal dobbeltsjekke 👍 

Edit: Dobbeltsjekka, er ikke verdt tiden det tar å fikse siden det er en veldig ulogisk situasjon å befinne seg i og siden det er midlertidig.

2022-10-26 11:25 UTC, thanglyphan commented on src/sider/opprettnysak/komponenter/oppgaveVelger.tsx
> +              change("oppgaveID", null);
Sant :p

2022-10-27 11:49 UTC, thanglyphan approved these changes
Da ser valideringen meget bra ut

2022-10-27 11:58 UTC, merged