6009 TOGGLE DAPI kopiering av trygdeavgiftssteget ny vurdering
navikt/melosys-web pull request #2039
Opened 2023-09-27 08:12 UTC by fredrik-oh

https://jira.adeo.no/browse/MELOSYS-6009
Kopiering av trygdeavgiftssteget skjer i backend. Endringene her omfatter refaktorering av skatteplikt. Skatteplikt registreres nå i perioder på lik linje som inntektskilder.

2023-09-27 08:38 UTC, thanglyphan commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    const inntektskilder = formVerdier.inntektskilder.map((inntektskilde: Inntektskilde) => ({
Ser at vi bruker mer termen formValues, vi bør være konsekvente

2023-09-27 08:42 UTC, thanglyphan commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/komponenter/skatteforholdsperioder.tsx
> +        <Nav.Row className="skatteforholdsperioder__overskriftrad">
Bruke tabell fra aksel? Eller er dette noe annet

2023-09-27 09:14 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/komponenter/skatteforholdsperioder.tsx
> +        <Nav.Row className="skatteforholdsperioder__overskriftrad">
Ikke en tabell ref. diskusjonen vi hadde om gruppering av input felt og hvorvidt det stemmer overens med mdn docs definisjon av tabell

2023-09-27 09:14 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    const inntektskilder = formVerdier.inntektskilder.map((inntektskilde: Inntektskilde) => ({
Bruker formVerdier her da formValues allerede er i scopet. E: Dette er oppdaterte verdier fra react-hook-form, men formValues kan være utdatert i det denne effecten kjøres pga debouncing

2023-09-27 09:33 UTC, thanglyphan commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/komponenter/skatteforholdsperioder.tsx
> +        <Nav.Row className="skatteforholdsperioder__overskriftrad">
Det er sant

2023-09-27 09:34 UTC, thanglyphan commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    const inntektskilder = formVerdier.inntektskilder.map((inntektskilde: Inntektskilde) => ({
Ah, ok skjønner

2023-09-27 09:34 UTC, thanglyphan approved these changes

2023-09-27 09:44 UTC, barstadEkstern approved these changes

2023-09-27 12:18 UTC, janitamarielle requested changes
inntekstkilde skal være med uavhengig av skatteplikttype. Før var det slik at vi kunne lagre skatteplikttype før vi fullførte/fikk gyldige inntekstkilder

2023-09-27 12:18 UTC, janitamarielle commented on src/services/modules/trygdeavgift.ts
> +  skatteforholdList: Skatteforhold[];
skatteforhold*?

2023-09-27 12:18 UTC, janitamarielle commented on src/services/modules/trygdeavgift.ts
> +  skatteforholdList: Skatteforhold[];
Eller skatteforholdsperiode hvis du vil vise at det er flertall?

2023-09-27 12:18 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/komponenter/skatteforholdsperioder.tsx
> +                  onChange={(value) => handleEndreTom(index, value)}
Legge til fom-dato som minDate?

2023-09-27 12:18 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    skatteforholdList?.find(
Istedenfor Boolean + find, bruke some?

2023-09-27 12:18 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +          : [innvilgetPeriode || {}]
Hva gjør egentlig denne? Er ikke innvilgetPeriode en medlemskapsperiode? Altså ikke riktig format?

2023-09-27 12:18 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    setLagrePending(true);
Ville antatt denne var ved toppen av funksjonen 🤷‍♀️

2023-09-27 12:18 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +      inntektskilder: erBrukerSkattepliktig(formVerdier.skatteforholdList) ? inntektskilder : [],
Man skal ha inntektskilder også når man ikke er skattepliktig?

2023-09-27 12:24 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +          : [innvilgetPeriode || {}]
Kode fra tidligere pull request. Er et objekt med fomDato og tomDato felt som er gyldig ovenfor schema definisjon for skatteforhold. Beregnes i finnInnvilgetMedlemskapsperiode, kunne kanskje vært navngitt bedre ja

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/komponenter/meldinger.tsx
> +  if (skatteforholdsperioder.length === 0) return false;
Sjekk om både skatteforholdsperioder og medlemskapsperioder er empty. Fikk feil i test for tilsvarende for inntektskildeperiodene.

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +      resetskatteforholdsperioder(
Stor S

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +          : [innvilgetPeriode || {}]
Renamer du funksjonen? defaultFomTom bare er vel bedre.

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    if (redigerbart) setTrygdeavgift(undefined);
Dette blir ikke funky når du går inn på en behandling med allerede beregnet trygdeavgift?

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +            defaultPeriode={defaultPeriode}
Støtter denne endring i medlemskapsperioden etter Perioder-steget ble gyldig? Gjelder også selve skatteforholdsperiodene og inntekstkildene, nå som fom og tom vises i frontend.

Var en oppgave som oppdarterte fom og tom på nevnte perioder ved endring på medlemskapsperiodene, men dette var før fom og tom-feltene kom inn i trygdeavgift-steget.

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +      {skalBeregneForelopigTrygdeavgift && (
Hvorfor o?

2023-09-29 09:59 UTC, janitamarielle commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgiftSchema.jsx
> +    const erBrukerSkattepliktigIHelePerioden = !skatteforholdsperioder.some(
Denne funksjonen ser lik ut den som er brukt i inntekstkilde. Kan den dras ut i egen funksjon og brukes av begge? Tilsvarende bruttoInntektKreves?

2023-09-29 10:32 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +      {skalBeregneForelopigTrygdeavgift && (
just cause

2023-09-29 12:24 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +    if (redigerbart) setTrygdeavgift(undefined);
Fikser

2023-09-29 12:27 UTC, fredrik-oh commented on src/sider/ftrl/saksbehandling/stegKomponenter/vurderingTrygdeavgift/vurderingTrygdeavgift.tsx
> +            defaultPeriode={defaultPeriode}
Håndteres i https://jira.adeo.no/browse/MELOSYS-6148
Har lagt inn kommentar

2023-09-29 14:08 UTC, janitamarielle approved these changes
Tag med TOGGLE

Har ikke kjørt det opp lokalt og sjekket. Skal jeg gjøre det i tillegg?

2023-09-29 14:51 UTC, merged