6035 Fikser adressefeilmelding ved avsender:annen
navikt/melosys-web pull request #2067
Opened 2023-10-13 08:03 UTC by bergande

2023-10-13 08:29 UTC, fredrik-oh requested changes

2023-10-13 08:29 UTC, fredrik-oh commented on src/sider/journalforing/komponenter/sendForvaltningsMelding.tsx
> +      {harRegistrertAdresse === false && (
🤔 Edit: Litt uklart med en emote som kommentar,  men denne endringen er vel unødvendig? Ingen dealbreaker altså 😄

2023-10-13 08:29 UTC, fredrik-oh commented on src/sider/journalforing/komponenter/journalforingform.jsx
> +          return;
return i useEffect skal være en cleanup function som rydder bort evt. subscriptions/event listeners i komponenten. Finn en måte å restrukturere if conditionsene uten å trenge return

2023-10-13 09:26 UTC, janitamarielle commented on src/sider/journalforing/komponenter/journalforingform.jsx
> +          return;
Kan bare dra ut alt i useEffect til en egen funksjon da eventuelt

2023-10-16 10:34 UTC, fredrik-oh approved these changes

2023-10-16 13:02 UTC, merged