6592 Tilpasninger artikkel 16.1 steget
navikt/melosys-web pull request #2308
Opened 2024-05-06 10:36 UTC by janitamarielle

https://jira.adeo.no/browse/MELOSYS-6592

Skriver ikke toggler siden jeg rører prod-kode

Venter på kodeverk-PR: https://github.com/navikt/melosys-kodeverk/pull/393

2024-05-06 13:45 UTC, fredrik-oh requested changes
Ønsker noen justeringer for å forbedre lesbarheten

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/tidligereMedlemskap.tsx
> +  <div>
Unødvendig div?

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/tidligereMedlemskap.tsx
> +    <div>
unødvendig div?

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/vurderingArtikkel16Anmodning.tsx
> +  return (
Kan vi dele opp denne filen?
F. eks. skille ut skjemainnholdet i en vurderingArtikkel16AnmodningForm?

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/vurderingArtikkel16Anmodning.tsx
> +              data-cy="unntakArtikkel"
cypress rusk, slett

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/vurderingArtikkel16Anmodning.tsx
> +              data-cy="begrunnelse"
cypress rusk

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/vurderingArtikkel16Anmodning.tsx
> +        <Nav.Row>
Renderer et par unødvendige diver her dersom behandling ikke er redigerbar. Flytt bool condition opp?

2024-05-06 13:45 UTC, fredrik-oh commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/tidligereMedlemskap.tsx
> +  return <Mui.Checkbox disabled={!redigerbart} onCheck={() => onChange(periodeID)} label={label} checked={checked} />;
Unødvendig oppdeling av jsx. Flytt inn i .map kallet i linje 49

2024-05-07 05:27 UTC, janitamarielle commented on src/sider/eu_eøs/stegKomponenter/vurderingArtikkel16Anmodning/vurderingArtikkel16Anmodning.tsx
> +  return (
eslinten var bare noe som hang igjen. Syns det ble bedre når vi fjernet endel som ikke trengtes. Thoughts?

2024-05-07 09:00 UTC, fredrik-oh approved these changes

2024-05-07 09:45 UTC, merged