6859 Ikke hvis fritekstfelt for sed hvis sokkelEllerSkip
navikt/melosys-web pull request #2464
Opened 2024-09-30 13:35 UTC by thomasdolplads

https://jira.adeo.no/browse/MELOSYS-6859

Ved sokkel/skip ikke vis sed fritekstfelt

2024-09-30 14:04 UTC, barstadEkstern requested changes

2024-09-30 14:04 UTC, barstadEkstern commented on src/sider/eu_eøs/stegKomponenter/vurderingVedtak/vurderingVedtak.tsx
> +        {redigerbart && !bucLukketOgLovvalgNorge && !erSokkelSkip && (
Tror det er kun for 11.3a att vi ønsker å gjemme fritekstfeilt. Denne endringen vil vel gjemme det for alle sokkel/skip?

2024-10-01 08:13 UTC, barstadEkstern approved these changes

2024-10-01 08:13 UTC, barstadEkstern commented on src/sider/eu_eøs/stegKomponenter/vurderingVedtak/vurderingVedtak.tsx
> +  const skalViseFritekstSed = () => {
Skriv det heller bare som en variabel
`const skalViseFritekstSed = !(bucLukketOgLovvalgNorge || (erSokkelSkip && erArtikkel11_3));`

2024-10-01 09:44 UTC, thomasdolplads commented on src/sider/eu_eøs/stegKomponenter/vurderingVedtak/vurderingVedtak.tsx
> +  const skalViseFritekstSed = () => {
ja lurt!

2024-10-01 09:51 UTC, merged