6808 Listekomponent fra aksel
navikt/melosys-web pull request #2475
Opened 2024-10-16 08:40 UTC by thomasdolplads

https://jira.adeo.no/browse/MELOSYS-6808
Det er ønsket at vi benytter redusert margin i lister generelt i Melosys, opprettet i den forbindelse en felleskomponent som kan benyttes som tar utgangspunkt i akselkomponenten for liste

2024-10-16 10:22 UTC, thanglyphan commented on src/felleskomponenter/liste/melListe.tsx
> +export const MelList = ({ title, size = "small", children }: MelListProps) => {
Hvorfor er det nødvendig med en ny komponent her? Kan vi ikke bare bruke list direkte?

2024-10-16 11:11 UTC, fredrik-oh requested changes
Se kommentar under Thangs kommentar for foreslåtte endringer.

2024-10-16 11:11 UTC, fredrik-oh commented on src/sider/trygdeavtale/stegKomponenter/vurderingFamilie/vurderingFamilie.tsx
> +            <div>{OBS_TEKST}</div>
Hvorfor en div her? Bruk `<br/>` hvis du trenger linjeskift.

2024-10-16 11:11 UTC, fredrik-oh commented on src/felleskomponenter/liste/melListe.tsx
> +export const MelList = ({ title, size = "small", children }: MelListProps) => {
Helt greit med en egen skallkomponent som vi har gjort for andre aksel komponenter, men den må plasseres riktig sted og følge samme format mtp. styling og typesetting. Skal ligge under navFrontend. Se på navFrontend/table for overstyring av subcomponents, se på navFrontend/textfield for hvordan vi håndterer styling.

2024-10-16 11:27 UTC, thanglyphan commented on src/felleskomponenter/liste/melListe.tsx
> +export const MelList = ({ title, size = "small", children }: MelListProps) => {
Ah, ja.. aksel list defaulter til medium, jeg ser hvorfor det er nødvendig nå :)

2024-10-16 14:29 UTC, thomasdolplads commented on src/felleskomponenter/liste/melListe.tsx
> +export const MelList = ({ title, size = "small", children }: MelListProps) => {
Den er god da har jeg flytta på det

2024-10-16 14:30 UTC, thomasdolplads commented on src/sider/trygdeavtale/stegKomponenter/vurderingFamilie/vurderingFamilie.tsx
> +            <div>{OBS_TEKST}</div>
Etter ønske i figma, men jeg kan sikkert ta den bort

2024-10-16 14:55 UTC, fredrik-oh reviewed
Litt flere kommentarer, men enklest å ta en gjennomgang på kontoret i morgen.

2024-10-16 14:55 UTC, fredrik-oh commented on src/felleskomponenter/alertmeldinger/unntakHjelpetekst.tsx
> +import MelList from "../../navFrontend/melList/melList";
Import fra navFrontend/index, se hvordan navFrontend/table brukes av konsumenter

2024-10-16 14:55 UTC, fredrik-oh commented on src/navFrontend/melList/melList.less
> +.generate-mb-classes(@i) when (@i >= 0) {
hva skjer her? :thinking:

2024-10-16 14:55 UTC, fredrik-oh commented on src/navFrontend/melList/melList.tsx
> +import { List } from "@navikt/ds-react";
List as NavList

2024-10-16 14:55 UTC, fredrik-oh commented on src/navFrontend/melList/melList.tsx
> +const MelList = ({ title, size = "small", children }: MelListProps) => {
Rename til List her

2024-10-16 14:55 UTC, fredrik-oh commented on src/navFrontend/melList/melList.tsx
> +interface MelListProps {
Trenger ikke egne typedefinisjoner her, ta de direkte fra navikt/ds-react slik det er gjort i de andre skallkomponentene

2024-10-17 09:25 UTC, thomasdolplads commented on src/navFrontend/melList/melList.less
> +.generate-mb-classes(@i) when (@i >= 0) {
la inn de klassene vi behøvde i stede

2024-10-22 14:52 UTC, fredrik-oh approved these changes

2024-10-22 14:52 UTC, merged