Melosys 6955 opplysninger riktig semantisk kodet
navikt/melosys-web pull request #2513
Opened 2024-11-26 16:07 UTC by Mvbraathen

2024-11-29 10:33 UTC, thomasdolplads requested changes
Ser ut til at det er mulighet for å sløyfe de li'ene rundt lenker, ellers bra!

2024-11-29 10:33 UTC, thomasdolplads commented on src/felleskomponenter/sidemeny/linkgroup.tsx
> +        <MenyLink
Menylink har også li's

2024-12-02 08:58 UTC, IsaSalemHame commented on src/felleskomponenter/sidemeny/linkgroup.tsx
> +      <li key={linkLabel.split(" ").join("")}>
replace(" ", "")

2024-12-02 09:00 UTC, IsaSalemHame commented on src/felleskomponenter/sidemeny/linkgroup.tsx
> +      <li key={linkLabel.split(" ").join("")}>
evt .replace(/ /g, "") hvis man skal fjerne multi-spaces

2024-12-03 11:31 UTC, thomasdolplads approved these changes
Bra jobba!

2024-12-03 11:45 UTC, merged