6962 ny datovelger med feilmeldinger
navikt/melosys-web pull request #2530
Opened 2024-12-10 13:38 UTC by thomasdolplads

https://jira.adeo.no/browse/MELOSYS-6962

2024-12-16 09:09 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker.tsx
> +  label: string;
Tenker at det er best å bruke mye av @navikt/ds-react sine props her istedenfor å introdusere helt nye men de er tilsvarende. Jeg tok en rask sjekk og du kan fjerne label og hidelabel hvertfall, det finnes i DateInputProps.

Ta gjerne en titt her og se om du kan fjerne flere og heller bruke de som nav definerer

2024-12-16 12:33 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker.tsx
> +  defaultSelected,
defaultSelected er også en prop som finnes i DatePickerProps, hent den isteden med rest.defaultSelected

Ta inn ...rest i props, ellers er det ikke vits å Props & DatePickerProps hvis man ikke skal bruke DatePickerProps

2024-12-16 13:13 UTC, fredrik-oh requested changes
Enig med de endringene Thang har etterspurt

2024-12-16 13:13 UTC, fredrik-oh commented on src/felleskomponenter/forms/dateRangePicker.tsx
> +      return (
Overflødig rendermetode, bare å putte den inn i L193

2024-12-16 13:13 UTC, fredrik-oh commented on src/felleskomponenter/forms/dateRangePicker.tsx
> +const InnerDateRangePicker = ({
Foretrekker i utgangspunktet 1 komponent per fil. Litt utdatert do's and dont's dokument ligger her https://github.com/navikt/melosys-devops/blob/main/docs/utvikling-melosys-web.md

2024-12-18 09:39 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker/dateRangePicker.tsx
> +  label,
Du trenger ikke label her, fjern denne og alle andre props som ligger allerede definert hos nav. Se under for ett eksempel på hvordan du kan bruke rest

Det kan bli rotete og forvirrende om vi introduserer noe som allerede finnes

2024-12-18 09:39 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker/dateRangePicker.tsx
> +          label={<Bleed marginInline="6">{label}</Bleed>}
{rest.label}

2024-12-18 09:40 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker/dateRangePicker.tsx
> +          hideLabel={hideLabel}
{rest.hideLabel}

2024-12-18 10:05 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker/dateRangePicker.tsx
> +
Du kan destructe rest her, så blir det {label} istedenfor {rest.label}: const {label, hideLabel} = rest

Smak og behag, viktigste er å bruke det som allerede finnes. Gå gjennom `DateRangePickerProps` og se hva som allerede finnes og bruk det

2024-12-18 17:57 UTC, fredrik-oh approved these changes
Ikke en approval, men fjerner changes requested. Thang sørger for endelig QA

2024-12-19 08:10 UTC, thanglyphan approved these changes

2024-12-19 08:36 UTC, thanglyphan commented on src/felleskomponenter/forms/dateRangePicker/dateRangePicker.tsx
> +    defaultSelected: rest.defaultSelected as DateRange,
Kun defaultSelected her holder

2024-12-19 09:11 UTC, merged