MELOSYS-2125 frontendlogger journalforing gosys
navikt/melosys-web pull request #440
Opened 2019-01-28 12:09 UTC by abjolseth

Fjernet frontendlogger klage, da frontend ikke kan skille mellom egen backend og extern URI.
Slettet yarn.lock og package-lock.json og la dem til i .gitignore

2019-01-28 13:18 UTC, frans-a requested changes

2019-01-28 13:18 UTC, frans-a commented on src/sider/journalforing.js
> -    } else {
Du mangler noe tilsvarende i src/sider/sok.js

2019-01-29 11:26 UTC, abjolseth commented on src/sider/journalforing.js
> -    } else {
Fixed, refactored to gerneric queryparmLogger

2019-01-29 14:44 UTC, frans-a approved these changes
ACK

2019-01-31 09:15 UTC, merged