Melosys 2294 visning av brev art.16.1 er kun mulig hvis man trykker på stegvelgerikon
navikt/melosys-web pull request #472
Opened 2019-02-28 08:46 UTC by JohanSakshaug

2019-02-28 09:27 UTC, abjolseth commented on src/soknad-komponenter/stegvelger/stegKomponenter/vurderingArtikkel16.js
> +    await lagreVilkarHandler();
try/catch ?

2019-02-28 10:55 UTC, baskevold requested changes
Det ser ut som om lovvalgsperioden blir sendt inn for tidlig. (Tom payload)
componentDidUpdate blir ikke kjørt ved klikk på forhåndsvisning

2019-03-01 08:06 UTC, JohanSakshaug commented
> Det ser ut som om lovvalgsperioden blir sendt inn for tidlig. (Tom payload)
> componentDidUpdate blir ikke kjørt ved klikk på forhåndsvisning

Det kan løses ved å sjekke at feltet for lovvalgsbestemmelse er utfylt ved klikk på "Send brevene". Opprettet jira-sak på det, så kan det tas i en egen PR.

2019-03-04 10:01 UTC, baskevold approved these changes

2019-03-04 10:31 UTC, merged