MELOSYS-2304 - Legg til validering av felter i art16.1 anmodning steg
navikt/melosys-web pull request #473
Opened 2019-03-05 11:24 UTC by JohanSakshaug

Her har jeg forsøkt å bruke redux form sin validering først, men fikk det ikke helt til. Valgte derfor å gjøre valideringen manuelt i steg-komponenten, pga tidsbruk.

2019-03-08 08:28 UTC, baskevold commented on src/soknad-komponenter/stegvelger/stegKomponenter/vurderingArtikkel16.js
> +    const valid = this.props.tidligeremedlemskap.length !== 0;
Det bør kunne være mulig å forhåndsvise brev og fatte vedtak for brukere som ikke har tidligere medlemskap

2019-03-08 12:13 UTC, baskevold approved these changes

2019-03-11 09:09 UTC, abjolseth requested changes
Legg til kommentar for hvorfor 'null' er default.

2019-03-11 09:09 UTC, abjolseth commented on src/ducks/form/selectors.js
> +  lovvalgsperiode => lovvalgsperiode.unntakFraBestemmelse || null
|| null; gir det mening? Sjekkes det ekplisitt på null, er det "falsy" prinsippet nok; dvs 0, null, undefined, false

2019-03-11 10:47 UTC, abjolseth approved these changes
ACK

2019-03-11 11:16 UTC, merged