MELOSYS-2418 - Fjerner filtrering av feil utfyllt maritimt arbeid
navikt/melosys-web pull request #518
Opened 2019-03-27 09:58 UTC by sigbjorn-myhre

... og legger til advarsel dersom navn ikke er fyllt ut.

2019-03-27 11:02 UTC, baskevold commented on src/ducks/soknad/reducers.js
>            territorialfarvann: maritimtArbeid.territorialfarvann ? maritimtArbeid.territorialfarvann : null,
Ved tomme felter blir kun territorialfarvann sendt med null. De andre feltene blir ekskludert helt fra payload, og schema vil feile fordi den krever at de enten har verdi eller er null

2019-03-27 16:24 UTC, JohanSakshaug approved these changes

2019-03-28 20:13 UTC, abjolseth commented
![image](https://user-images.githubusercontent.com/3278663/55189484-5092ee80-519e-11e9-8634-83913bf7aee2.png)

2019-03-28 20:18 UTC, abjolseth requested changes
Crash må fixes! Er det fordi melosys-schema ikke er i sync, i.e, <> 1.7.0 ?
soknad/reducers.js er på ville veier. Er allt for mye mekke transformasjoner. Her må vi ta grep.

2019-05-08 14:38 UTC, baskevold commented
Lukkes pga mye konflikter, og at den heller bør implementeres med yup

2019-05-08 14:38 UTC, closed without merging