MELOSYS-2419 - Legge til og slette fullmektig
navikt/melosys-web pull request #519
Opened 2019-03-27 15:07 UTC by JohanSakshaug

2019-03-27 15:57 UTC, abjolseth commented on src/soknad-komponenter/fullmektig/fullmektig.js
> +    if (fullmektig.representererKode) settRepresentererKode(fullmektig.representererKode);
Bra 👍

2019-03-28 12:17 UTC, baskevold commented on src/soknad-komponenter/fullmektig/fullmektig.js
>          <Nav.Fieldset disabled={!redigerbart} legend="Hvem er dette fullmektig for?" className="radioknapper">
Burde dette også skjules hvis ikke orgnr eksisterer?
org &&

2019-03-28 13:28 UTC, JohanSakshaug commented on src/soknad-komponenter/fullmektig/fullmektig.js
>          <Nav.Fieldset disabled={!redigerbart} legend="Hvem er dette fullmektig for?" className="radioknapper">
SokFullmektigOrg er dialogen for å søke etter orgnr for en fullmektig, så den må vises dersom det ikke er satt noen org enda.

2019-03-28 13:35 UTC, abjolseth requested changes
Oppdatere unit test(er) etter splitting av fullmektig.js

2019-03-28 13:35 UTC, abjolseth commented on src/soknad-komponenter/fullmektig/fullmektig.js
> +const SokFullmektigOrg = ({ lagreNyFullmektigOgOppdaterLokalt }) => {
const => function SokFullmektigOrg (...) {}

2019-03-28 19:54 UTC, abjolseth approved these changes
ACK.

2019-03-29 07:34 UTC, baskevold commented on src/soknad-komponenter/fullmektig/fullmektig.js
>          <Nav.Fieldset disabled={!redigerbart} legend="Hvem er dette fullmektig for?" className="radioknapper">
Jeg satt kommentaren på fieldset for "Hvem er dette fullmektig for?" - ikke SokFullmektigOrg :)
Sjekket UX-skissen, der var den heller ikke tegnet før gyldig orgnr var funnet

2019-03-29 08:41 UTC, JohanSakshaug commented on src/soknad-komponenter/fullmektig/fullmektigPanel.js
> +                key={uuid()} // Kan ikke bruke databaseID her da den er nullable
DatabaseID som vi får fra backend er ikke nullable

2019-03-29 17:16 UTC, JohanSakshaug commented on src/soknad-komponenter/fullmektig/fullmektig.js
>          <Nav.Fieldset disabled={!redigerbart} legend="Hvem er dette fullmektig for?" className="radioknapper">
Fikset

2019-04-01 13:05 UTC, merged