MELOSYS-2526 opprinnelig lovvavalgsperiode
navikt/melosys-web pull request #551
Opened 2019-04-24 11:14 UTC by abjolseth

2019-04-24 11:18 UTC, abjolseth commented
For å teste så:
endre fagsaker/snr-4.json og siste linje med behandlingstype: {"kode": "ENDRET_PERIODE"}

2019-04-24 11:20 UTC, abjolseth commented
![Skjermbilde 2019-04-24 kl  13 18 51](https://user-images.githubusercontent.com/3278663/56655646-a8d0e980-6693-11e9-95b8-14cd58fcb613.png)

2019-04-24 11:52 UTC, JohanSakshaug reviewed
![Screenshot from 2019-04-24 13-50-56](https://user-images.githubusercontent.com/46343153/56657373-21d24000-6698-11e9-8177-250596c964a0.png)

Ser ut som det mangler en fil.

2019-04-26 10:19 UTC, JohanSakshaug requested changes

2019-04-26 10:19 UTC, JohanSakshaug commented on src/soknad-komponenter/stegvelger/stegKomponenter/vurderingEndrePeriode.js
> +    await this.hentOpprinneligPeriode(4);
Her må behandlingsID brukes

2019-04-26 10:19 UTC, JohanSakshaug commented on src/soknad-komponenter/stegvelger/stegKomponenter/vurderingEndrePeriode.js
> +      this.validerPeriode();
Det burde kjøres this.validerTomDato(); etter this.validerPeriode(); for å trigge mulig felimelding for dato også

2019-04-26 11:26 UTC, rgraneru approved these changes

2019-04-26 11:42 UTC, baskevold commented on src/soknad-komponenter/stegvelger/stegKomponenter/vurderingEndrePeriode.js
> +    await this.hentOpprinneligPeriode(behandlingID);
Ser ikke behovet for await i componentDidMount

2019-04-26 11:48 UTC, JohanSakshaug approved these changes

2019-04-26 11:50 UTC, merged