MELOSYS-2087 registrering av unntaksperiode
navikt/melosys-web pull request #607
Opened 2019-06-17 14:03 UTC by abjolseth

2019-06-18 13:16 UTC, AStrand94 commented on src/services/modules/saksflyt/unntaksperioder.js
> +export const anmodning = behandlingID => {
Anmodning? Den har vi ikke

2019-06-18 13:30 UTC, JohanSakshaug commented on src/registrering-komponenter/saksopplysninger.js
> -      .catch(err => console.error(err));
Frontendlogger kan brukes her i stedet for console.error.

2019-06-19 13:43 UTC, JohanSakshaug requested changes

2019-06-19 13:43 UTC, JohanSakshaug commented on src/ducks/avklartefakta/selectors.js
> +    alleAvklartefakta.find(avklaring => avklaring.avklartefaktaKode === 'VURDERING_UNNTAK_PERIODE') || {}
Lag en 'VURDERING_UNNTAK_PERIODE' kode i frontend sitt kodeverk.

2019-06-19 13:43 UTC, JohanSakshaug commented on src/registrering-komponenter/saksopplysninger.js
> +          history.push('/');
Lag en metode for history.push('/') og pass den til then(). Det samme gjelder noen linjer ned.

2019-06-19 13:43 UTC, JohanSakshaug commented on src/registrering-komponenter/saksopplysninger.js
> +        }).catch(err => Utils.logger.error(err));
Du kan forkorte catch til catch(Utils.logger.error). Det samme gjelder noen linjer ned.

2019-06-19 13:43 UTC, JohanSakshaug commented on src/registrering-komponenter/saksopplysninger.js
> +                      readOnly
Jeg kan ikke finne readOnly som et prop på https://design.nav.no/components/input/technical. Finner det heller ikke i kildekoden til nav.input. Mente du disabled?

2019-06-19 13:43 UTC, JohanSakshaug commented on src/sider/registrering.js
> +// import SideOppsummering from '../soknad-komponenter/sideOppsummering';
Fjern kommentar

2019-06-19 13:43 UTC, JohanSakshaug commented on src/sider/registrering.js
> +// import * as Api from '../services/api';
Fjern kommentar

2019-06-19 13:43 UTC, JohanSakshaug commented on src/sider/registrering.js
> +// import { formSelectors } from '../ducks/form';
Fjern kommentar

2019-06-19 13:43 UTC, JohanSakshaug commented on src/sider/registrering.js
> +  /*
Fjern kommentar

2019-06-19 13:43 UTC, JohanSakshaug commented on src/sider/registrering.js
> +              {/*
Fjern kommentar

2019-06-20 08:42 UTC, merged