MELOSYS-2912 - Opprette H-BUC
navikt/melosys-web pull request #656
Opened 2019-08-14 13:04 UTC by sigbjorn-myhre

2019-08-16 08:33 UTC, JohanSakshaug requested changes
Melosys krasjer når man velger "Velg..." for fagområde under "Opprett ny buc"-tab.

2019-08-16 08:33 UTC, JohanSakshaug commented on src/felleskomponenter/sideDialog/sedBestilling.js
> +const lovvalgEllerHorisontalSektor = sektor => sektor.kode === 'LA' || sektor.kode === 'HZ';
Kommer disse kodene fra et kodeverk?

2019-08-16 08:37 UTC, sigbjorn-myhre commented on src/felleskomponenter/sideDialog/sedBestilling.js
> +const lovvalgEllerHorisontalSektor = sektor => sektor.kode === 'LA' || sektor.kode === 'HZ';
Kommer fra et internt kodeverk (eessikodeverk.json). Jeg og Are har snakket om å opprette et felles eessi-kodeverk for nEESSI og Melosys. Jeg skal fikse bugen med "Velg...".

2019-08-16 10:03 UTC, JohanSakshaug commented on src/felleskomponenter/sideDialog/sedBestilling.js
> +const lovvalgEllerHorisontalSektor = sektor => sektor.kode === 'LA' || sektor.kode === 'HZ';
Kunne du referert til kodeverket her, slik at det blir lettere å se hvor kodene kommer fra? For eksempel kan du importere essikodeverk.json og bruke den som et js-objekt. Eller bruke en selector.

Synes også at essikodeverk.json hadde ligget bedre plassert under src/kodeverk.

2019-08-19 11:01 UTC, sigbjorn-myhre commented
Venter med denne til https://github.com/navikt/melosys-eessi-kodeverk er oppe og gå. Da retter jeg etter Johan sine ønsker med nytt kodeverk.

2019-08-20 12:23 UTC, abjolseth commented on src/kodeverk/eessiKodeverkHelper.js
> +  return [kodeTilObjekt(EKV.Koder.sedtyper[alleBuc2Seds[buc]], EKV.KTObjects.sedtyper)];
Denne funksjonaliteten bør implementeres i eessi-kodeverk!!!

2019-08-20 12:24 UTC, abjolseth commented on src/kodeverk/eessiKodeverkHelper.js
> +  return EKV.KTObjects.buctyper[EKV.kodemaps.SEKTOR2BUC[fagomrade]];
Implementeres i eessi-kodeverk

2019-09-10 14:21 UTC, abjolseth approved these changes
ACK

2019-09-10 14:23 UTC, JohanSakshaug approved these changes

2019-09-10 14:23 UTC, merged