Melosys-3266 - Videresend soknad fritekst
navikt/melosys-web pull request #771
Opened 2019-11-08 15:50 UTC by JohanSakshaug

- Fritekst for videresending sendes nå til henlegg-videresend endepunkt.
- IKKE_BOSATT_NORGE-fakta fjernes.
- Lagt til jest-prop-type-error i setupTests.js. Feiler tester hvor det kastes proptype-errors.

2019-11-08 15:54 UTC, abjolseth approved these changes
ACK

2019-11-11 13:52 UTC, sigbjorn-myhre approved these changes

2019-11-11 13:59 UTC, sigbjorn-myhre requested changes
Ser at henlegg-videresend er endret til POST, men den står fortsatt som PUT i backend

2019-11-11 14:37 UTC, JohanSakshaug commented
@sigbjorn-myhre Ok. Da avventer jeg backend.

2019-11-12 09:23 UTC, sigbjorn-myhre approved these changes

2019-11-12 09:48 UTC, merged