MELOSYS-3564 - Sortering innsyn i sak
navikt/melosys-web pull request #941
Opened 2020-05-13 07:50 UTC by sigbjorn-myhre

Legger til sortering av fagsaker i innsyn i sak-bildet

2020-05-13 10:38 UTC, JohanSakshaug requested changes

2020-05-13 10:38 UTC, JohanSakshaug commented on src/sider/sok/sok.js
> +import OppgaverMedSortering from '../forside/komponenter/mineoppgaver/oppgaver';
Jeg synes Oppgaver-komponenten (OppgaverMedSortering) burde flyttes til felleskomponenter, slik at vi slipper at sider/sok er avhengig av sider/forside.

2020-05-13 15:34 UTC, JohanSakshaug reviewed
Kunne ikke OppgaverMedSortering egentlig vært mer generell, og blitt renamet til ListeMedSortering(eller SortableList)?  Den har jo egentlig ingen avhengighet mot strukturen på en oppgave, og nå brukes den jo både til fagsaker(søk) og oppgaver(forside). Kunne ligget rett under felleskomponenter/listeMedSortering. Og sortOppgaverByDate -> sortItemsByDate.
Hva tenker du?

2020-05-14 08:26 UTC, sigbjorn-myhre commented
Enig der! 👍

2020-05-14 09:26 UTC, JohanSakshaug requested changes
Begynner å se bra ut, bare noen flere renames så er det good tenker jeg

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterElementerEtterDato.js
> +const sorterElementerEtterDato = (order, dateFieldPath) => (forsteOppgave, andreOppgave) => {
`(forsteOppgave, andreOppgave)` -> `(forsteElement, andreElement)`

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterElementerEtterDato.test.js
>  describe('sortOppgaverByDate', () => {
sorterElementerEtterDato*

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterbarListe.test.js
>  describe('Oppgaver', () => {
SorterbarListe

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterbarListe.test.js
>    it('kan sortere slik at nyeste oppgave kommer først', () => {
oppgave -> element

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterbarListe.test.js
>    it('kan sortere slik at eldste oppgave kommer først', () => {
oppgave -> element

2020-05-14 09:26 UTC, JohanSakshaug commented on src/felleskomponenter/sorterbarListe/sorterbarListe.test.js
>    it('viser ingenting hvis oppgaver er falsy', () => {
oppgaver -> elementer

2020-05-14 10:25 UTC, JohanSakshaug approved these changes
👍

2020-05-14 10:48 UTC, merged