MELOSYS-3745 - feil trygdedekning utland utpekt
navikt/melosys-web pull request #942
Opened 2020-05-13 12:27 UTC by sigbjorn-myhre

Setter rett trygdedekning når utland er utpekt

2020-05-13 15:05 UTC, JohanSakshaug approved these changes

2020-05-13 21:47 UTC, AStrand94 requested changes

2020-05-13 21:47 UTC, AStrand94 commented on src/ducks/lovvalgsperioder/operations.js
>      medlemskapstype: MKV.Koder.medlemskapstyper.PLIKTIG,
`medlemskapstype: MKV.Koder.medlemskapstyper.UNNTATT`.
Dette kunne egentlig fint vært fjernet fra POST-en og vært avklart av backend.. Regelen er jo per nå bare om lovvalgslandet er NO eller ikke 🙄

2020-05-14 08:27 UTC, sigbjorn-myhre commented on src/ducks/lovvalgsperioder/operations.js
>      medlemskapstype: MKV.Koder.medlemskapstyper.PLIKTIG,
Mener du at backend kan avklare både trygdedekning og medlemskapstype?

2020-05-14 08:33 UTC, AStrand94 commented on src/ducks/lovvalgsperioder/operations.js
>      medlemskapstype: MKV.Koder.medlemskapstyper.PLIKTIG,
Ja, og `BURDE` egentlig gjøre det, så enkel logikken for det er nå. Jeg vet ikke om vi kommer til å få tilfeller hvor lovvalgsland=NO og dekning=UNNTATT (tviler på Medl aksepterer det heller).
Men det blir en litt vel stor refaktorering per nå. Så jeg synes egentlig ikke vi bør gjøre det nå.. Mer jeg som sitter og tenker høyt.. 😅

2020-05-14 08:50 UTC, sigbjorn-myhre commented on src/ducks/lovvalgsperioder/operations.js
>      medlemskapstype: MKV.Koder.medlemskapstyper.PLIKTIG,
hehe, skjønner. Men da gjelder samme regler for medlemskapstype pliktig/unntatt som med trygdedekning, ikke sant?

2020-05-14 10:32 UTC, AStrand94 commented on src/ducks/lovvalgsperioder/operations.js
>      medlemskapstype: MKV.Koder.medlemskapstyper.PLIKTIG,
Stemmer!

2020-05-14 11:55 UTC, AStrand94 approved these changes

2020-05-14 11:55 UTC, merged